version: '3.4'
services:

  db:
    image: postgres
    ports:
    - "5432:5432"
    environment:
      POSTGRES_DB: ttest
      POSTGRES_PASSWORD: ttest123
    networks:
     ttest_nework:
        aliases:
          - db
    restart: always
  api_server:
    depends_on:
    - "db"
    build:
      context: .
      dockerfile: Dockerfile
    command:  start
    ports:
    - "3000:3000"
    networks:
    - ttest_nework


networks:
  ttest_nework:
    driver: bridge

