version: '3.4'
services:

  db:
    image: postgres
    ports:
    - "5432:5432"
    environment:
      POSTGRES_DB: ttest
      POSTGRES_PASSWORD: ttest123
    networks:
    - ttest
    restart: always



networks:
  ttest:
    driver: bridge

